
- name: checkout code
  uses: actions/checkout@v2
- name: Setup Mambaforge
  uses: conda-incubator/setup-miniconda@v2
    with:
      miniforge-variant: Mambaforge
      miniforge-version: latest
      activate-environment: qmlcourse.ai
      use-mamba: true
            
