name: create-requirements
# This action creates anaconda env requirements.yml and environment-yml artifact file for continious intergation and docker needs.
# action starts in deploy-book, deploy-branch, test-docker workflows
on:
  workflow_dispatch:

jobs:
  create_requirements:
    runs-on: ubuntu-latest
    env:
      TF_CPP_MIN_LOG_LEVEL: 3

    steps:
      - name: checkout branch for build
        uses: actions/checkout@v2

      - name: checkout branch with cache
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: ./gh-pages

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: qml-dev
          channels: psi4/label/dev, conda-forge, defaults
          environment-file: tools/environment.yml
          use-mamba: true
          channel-priority: true
          use-only-tar-bz2: true

      - name: install the main dependencies
        run: |
          conda run -n qml-dev poetry install

      # todo: replace with a more sane solution
      - name: install tensorflow_quantum # https://www.tensorflow.org/quantum/install
        run: |
          conda run -n qml-dev pip install --upgrade pip
          conda run -n qml-dev pip install -U tensorflow==2.5.1
          conda run -n qml-dev pip install -U tensorflow_quantum
          conda run -n qml-dev pip install -U tfq-nightly

      - name: create requirements.yml
        run: conda run -n qml-dev conda env export > environment.yml

      # Not working in other workflows, todo
      # - name: Upload output file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: environment-yml
      #     path: environment.yml

      - name: change file name requirements.yml to requirements-ubuntu.yml
        id: add_suffix_linux
        run: |
          mv environment.yml requirements-ubuntu.yml
      - name: commit new requirements.yml
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add requirements-ubuntu.yml

      - name: push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
