name: create-requirements

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  create_requirements:
    runs-on: ubuntu-latest
    env:
      TF_CPP_MIN_LOG_LEVEL: 3

    steps:
      - name: checkout branch for build
        uses: actions/checkout@v2

      - name: checkout branch with cache
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: ./gh-pages
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: qmlcourse.ai
          environment-file: tools/environment.yml
          use-mamba: true
      - name: install the main dependencies
        run: |
          conda run -n qmlcourse.ai poetry install

      # todo: replace with a more sane solution
      - name: install tensorflow_quantum # https://www.tensorflow.org/quantum/install
        run: |
          conda run -n qmlcourse.ai pip install --upgrade pip
          conda run -n qmlcourse.ai pip install -U tensorflow==2.5.1
          conda run -n qmlcourse.ai pip install -U tensorflow_quantum
          conda run -n qmlcourse.ai pip install -U tfq-nightly

      - name: create requirements.yml
        run: conda run -n qmlcourse.ai conda env export > environment.yml
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: environment-yml-file
          path: environment.yml
      - name: change file name requirements.yml to requirements-linux.yml
      id: add_suffix_linux
      run: |
        mv requirements.yml requirements-linux.yml
      - name: commit new requirements.yml
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add environment.yml
    - name: push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}