name: deploy-book

on:
  workflow_dispatch:
    inputs:
      DisableCache:
        description: 'Disable cache'
        required: false
        default: 'false'
  push:
    branches: [ master ]

jobs:

  deploy_book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/qmlcourse.ai

          # - os: macos-latest
          #   label: osx-64
          #   prefix: /Users/runner/miniconda3/envs/qmlcourse.ai

          # - os: windows-latest
          #   label: win-64
          #   prefix: C:\Miniconda3\envs\qmlcourse.ai
    env:
      TF_CPP_MIN_LOG_LEVEL: 3

    steps:
      - name: checkout branch for build
        uses: actions/checkout@v2

      - name: checkout branch with cache
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: ./gh-pages

      - name: copy cache for build book
        if: ${{ github.event.inputs.DisableCache != 'true' }}
        run: |
          cp -r ./gh-pages/_build/ ./qmlcourseRU/ || exit 0

      - name: check locking files
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
             poetry.lock
             pyproject.toml

      - name: create or change environment-yml and requirements-*.ymls
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: ./.github/workflows/create-requirements.yml

        # If files is changed
      - name: download a new requirements.yml artifact
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: actions/download-artifact@v2
        with:
          name: environment-yml
        # Else - use from checkout
      - name: copy requirements-linux.yml to environment.yml
        if: steps.changed_files.outputs.files_changed == 'true'
        run: cp requirements-linux.yml environment.yml

      # - name: Cache conda
      #   uses: actions/cache@v2
      #   env:
      #     # Increase this value to reset cache if environment.yml has not changed
      #     CACHE_NUMBER: 0
      #   with:
      #     path: ~/conda_pkgs_dir
      #     key:
      #       ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
      #       hashFiles('environment.yml') }}
      # - name: install mamba
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     activate-environment: qmlcourse.ai
      #     channels: psi4/label/dev, conda-forge, defaults
      #     channel-priority: strict
      #     environment-file: environment.yml
      #     use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: install mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: qmlcourse.ai
          use-mamba: true
          python-version: 3.8
          channels: psi4/label/dev, conda-forge, defaults
          channel-priority: true
          use-only-tar-bz2: true

      # - name: copy cache dir for dependecies
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-poetry-modules
      #   with:
      #     path: .venv
      #     key: venv2-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      # Use cache
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}
        id: mamba-cache

      # # Update environment if cache does not exist
      # - name: Update environment
      #   run: mamba env update -n qmlcourse.ai -f environment.yml
      #   if: steps.cache.outputs.cache-hit != 'true'
      - name: install mamba with all packages if we miss the cache
        uses: conda-incubator/setup-miniconda@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: qmlcourse.ai
          use-mamba: true
          python-version: 3.8
          channels: psi4/label/dev, conda-forge, defaults
          channel-priority: true
          use-only-tar-bz2: true
          environment-file: environment.yml

      - name: build the book
        run: |
          export DWAVE_TOKEN="${{ secrets.DWAVE_TOKEN }}"
          poetry run jupyter-book build ./qmlcourseRU

      - name: fix sitemap
        run: |
          poetry run python ./tools/fix_sitemap.py ./qmlcourseRU/_build/html/sitemap.xml ./qmlcourseRU/_build/html/sitemap.xml

      - name: gh-pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourseRU

      - name: gh-pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourseRU/_build/html/
          publish_branch: pages-gh
